services:
  web:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - student-db:/data/db

volumes:
  student-db:
