GET http://localhost:3000/students

###

GET http://localhost:3000/students/1

###

POST http://localhost:3000/students
Content-Type: application/json

{
    "id": "01234",
    "name": "Tom"
}

###

POST http://localhost:3000/students
Content-Type: application/json

{
    "id": "56789",
    "name": "Jason",
    "gpa": 4.0,
    "year_enroll": 2020
}

###

GET http://localhost:3000/students/01234

###

GET http://localhost:3000/students/01235

###

DELETE http://localhost:3000/students/01234

###

DELETE http://localhost:3000/students/01235

###

PATCH http://localhost:3000/students/01234
Content-Type: application/json

{
    "gpa": 3.0
}