name: dev branch

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set date
        id: date
        run: echo "ACTION_DATE=$(date)" >> $GITHUB_OUTPUT
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to dev image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: guardianwang/student_api:dev
      - 
        name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x '.env' -x 'docker-compose.yml'
      - 
        name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_ACCESS_KEY }}
          application_name: web_student_db_service
          environment_name: Webstudentdbservice-env
          existing_bucket_name: webstudentdbservice-bucket
          version_label: app dev ${{ steps.date.outputs.ACTION_DATE }} ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
          wait_for_deployment: false
